openapi: 3.0.1
info:
  description: >-
    The Data Set API (DSAPI) allows the public users to discover and search
    USPTO exported data sets. This is a generic API that allows USPTO users to
    make any CSV based data files searchable through API. With the help of GET
    call, it returns the list of data fields that are searchable. With the help
    of POST call, data can be fetched based on the filters on the field names.
    Please note that POST call is used to search the actual data. The reason for
    the POST call is that it allows users to specify any complex search criteria
    without worry about the GET size limitations as well as encoding of the
    input parameters.
  version: 1.0.0
  title: USPTO Data Set API!!!
  contact:
    name: Open Data Portal
    url: 'https://developer.uspto.gov'
    email: developer@uspto.gov
paths:
  /animal/list:
    get:
      tags:
        - animal
      description: 動物一覧
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/animalSchemas/animal'
  '/animal/list/{code}':
    get:
      tags:
        - animal
      description: 動物取得
      parameters:
        - in: path
          name: code
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/animalSchemas/animal'
components:
  animalSchemas:
    animal:
      type: object
      properties:
        animal_name:
          type: string
          description: 動物の名前
        animal_code:
          type: string
          description: 動物コード
